### ISSUE TITLE
API for getting fund's expenses for user. 

### ISSUE THREAD

**Issue by titov-artem** [icekeeper/distributedfunds#2]
Need API for getting expenses transaction for user in fund.

Expecting dto with such fields: 
- date (String) - date of transaction
- name (String)- name of item, that was paid for by this transaction
- amount (Number/String)- amount of money that was spent on item
- user_amount (Number/String) - amount of money that was spent by current user
- participants (Array of ?) - users that spent moneys in this transaction. Each user can be described by login or full UserDto
- payer (?) - user that payed for item. Login or full UserDto

After implementing print here API url and final Dto version

**Comment by icekeeper** [comment]
[DTO](https://github.com/icekeeper/distributedfunds/blob/master/birthday/src/main/kotlin/ws/TransactionDto.kt) [API](https://github.com/icekeeper/distributedfunds/blob/master/birthday/src/main/kotlin/ws/routing/BirthdayTransactions.kt)

Added API methods:

- `GET /api/front/user/fund/{fundId}/transaction/gift?pageSize=10&pageNumber=1` - returns a list of current user gift transactions, `pageSize` and `pageNumber` parameters are optional.
- `GET /api/front/user/fund/{fundId}/transaction/redistribution?pageSize=10&pageNumber=1` - returns a list of current user redistributions transactions, `pageSize` and `pageNumber` parameters are optional.
- `POST /api/front/user/fund/{fundId}/transaction/gift` - creates new gift transaction for current user as a gift buyer with `CreateGiftTransactionRequest` DTO object in request body.
- `POST /api/front/user/fund/{fundId}/transaction/redistribution` - creates new redistribution transaction from current user to other user with `CreateRedistributionTransactionRequest` DTO object in request body.
- `POST /api/front/user/fund/{fundId}/transaction/{transactionId}/confirm` - confirms incoming transaction.
