### ISSUE TITLE
API for fund info for user

### ISSUE THREAD

**Issue by titov-artem** [icekeeper/distributedfunds#3]
Need API to get full information about fund on user's fund page.

Expecting such fields:
- id (Number) - fund id
- name (String) - fund name
- description (String) - fund description
- supervisor (?) - user, that is owner of this fund. Login or full UserDto
- users (Array of ?) - list of users, that are contributing to this fund. We need to think which objects will be in this array. It can be just logins, or full UserDto
- balance (Number/String) - current user's fund balance
- gradation (String) - gradation of user's balance among all fund's users balances

After implementing print here API url and final Dto version

**Comment by icekeeper** [comment]
Decided to represent fund participants as full UserDtos.
Balance value and gradation combine in one BalanceDto.

**Comment by icekeeper** [comment]
[API](https://github.com/icekeeper/distributedfunds/blob/master/birthday/src/main/kotlin/ws/routing/BirthdayFunds.kt) [DTO](https://github.com/icekeeper/distributedfunds/blob/master/birthday/src/main/kotlin/ws/dto.kt) 

Restructured fund API's a little. Now there are two distinct API methods for fetching fund – with or without balance. One for user's page and one for list of all funds.

User API endpoint is `/api/front/user/fund` for all user funds and `/api/front/user/fund/{fundId}` for specific fund.

All funds can be fetched by `/api/front/fund` and `/api/front/fund/{fundId}` accordingly.

Also method for creating a new fund now gets supervisor from session, not from request body.
